import type { 
  AnalyticsDashboard, 
  AdvancedAnalytics, 
  EnhancedDashboard,
  DetectedIssue,
  ServiceRanking,
  ParticipationMetrics,
  ComplaintSummary,
  DepartmentPerformance,
  ManagedIssue,
  AIInsight,
  WeeklySummary,
  ServiceHealth,
  ServiceParticipation,
  HistoricalComparison,
  AggregatedStudentVoice,
  ServiceOwner,
  Alert,
  SegmentedAnalytics,
  ServiceBenchmark,
  BenchmarkSummary,
  ParticipationInsight,
  ImprovementTimeline,
  OperationalDashboard,
} from "@/types/analytics";
import type { FeedbackRecord } from "@/types/feedback";
import { SERVICE_TO_DEPARTMENT_MAP, TOTAL_ENROLLED_STUDENTS } from "./constants";

// Generate dates for the last 14 days
function getRecentDates(days: number): string[] {
  const dates: string[] = [];
  for (let i = days - 1; i >= 0; i--) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    dates.push(`${String(date.getMonth() + 1).padStart(2, "0")}/${String(date.getDate()).padStart(2, "0")}`);
  }
  return dates;
}

const recentDates = getRecentDates(14);

export const MOCK_ANALYTICS: AnalyticsDashboard = {
  metrics: {
    totalFeedback: 1247,
    avgSatisfaction: 4.2,
    weeklyResponses: 156,
    topServiceScore: 4.7,
    totalFeedbackDelta: 12.5,
    avgSatisfactionDelta: 0.3,
    weeklyResponsesDelta: 8.2,
  },
  trends: recentDates.map((date, i) => ({
    date,
    score: 3.8 + Math.sin(i * 0.5) * 0.5 + Math.random() * 0.3,
    count: 8 + Math.floor(Math.random() * 15),
  })),
  ratingDistribution: [
    { rating: 1, count: 23 },
    { rating: 2, count: 45 },
    { rating: 3, count: 187 },
    { rating: 4, count: 456 },
    { rating: 5, count: 536 },
  ],
  serviceBreakdown: [
    {
      serviceId: "cafeteria",
      serviceName: "Cafeteria",
      avgScore: 4.2,
      totalFeedback: 312,
      trend: "up",
    },
    {
      serviceId: "library",
      serviceName: "Library",
      avgScore: 4.7,
      totalFeedback: 289,
      trend: "up",
    },
    {
      serviceId: "online-course",
      serviceName: "Online Course Portal",
      avgScore: 3.8,
      totalFeedback: 245,
      trend: "down",
    },
    {
      serviceId: "hostel",
      serviceName: "Hostel",
      avgScore: 3.9,
      totalFeedback: 198,
      trend: "stable",
    },
    {
      serviceId: "campus-event",
      serviceName: "Campus Events",
      avgScore: 4.5,
      totalFeedback: 203,
      trend: "up",
    },
  ],
};

// Generate some recent timestamps
function getRecentTimestamp(daysAgo: number, hoursAgo: number = 0): string {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  date.setHours(date.getHours() - hoursAgo);
  return date.toISOString();
}

export const MOCK_FEEDBACK: FeedbackRecord[] = [
  {
    _id: "fb001",
    studentId: "STU2024001",
    studentName: "Alice Johnson",
    serviceId: "cafeteria",
    serviceName: "Cafeteria",
    collegeId: "college-default-001",
    ratings: { quality: 5, variety: 4, cleanliness: 5, value: 4 },
    overallSatisfaction: 5,
    comment: "Great food options and very clean environment!",
    submittedAt: getRecentTimestamp(0, 2),
  },
  {
    _id: "fb002",
    studentId: "STU2024015",
    studentName: "Bob Smith",
    serviceId: "library",
    serviceName: "Library",
    collegeId: "college-default-001",
    ratings: { resources: 5, environment: 5, staff: 4, hours: 5 },
    overallSatisfaction: 5,
    comment: "Excellent study environment with great resources.",
    submittedAt: getRecentTimestamp(0, 5),
  },
  {
    _id: "fb003",
    studentId: "STU2024042",
    studentName: "Carol Davis",
    serviceId: "online-course",
    serviceName: "Online Course Portal",
    collegeId: "college-default-001",
    ratings: { usability: 3, content: 4, support: 3, reliability: 2 },
    overallSatisfaction: 3,
    comment: "Platform could be more stable during peak hours.",
    submittedAt: getRecentTimestamp(0, 8),
  },
  {
    _id: "fb004",
    studentId: "STU2024078",
    studentName: "David Wilson",
    serviceId: "hostel",
    serviceName: "Hostel",
    collegeId: "college-default-001",
    ratings: { cleanliness: 4, amenities: 3, security: 5, maintenance: 4 },
    overallSatisfaction: 4,
    comment: "Good security but needs better WiFi coverage.",
    submittedAt: getRecentTimestamp(1, 3),
  },
  {
    _id: "fb005",
    studentId: "STU2024103",
    studentName: "Eva Martinez",
    serviceId: "campus-event",
    serviceName: "Campus Events",
    collegeId: "college-default-001",
    ratings: { variety: 5, organization: 5, communication: 4, timing: 4 },
    overallSatisfaction: 5,
    comment: "Loved the tech fest! More events like this please.",
    submittedAt: getRecentTimestamp(1, 6),
  },
  {
    _id: "fb006",
    studentId: "STU2024089",
    studentName: "Frank Lee",
    serviceId: "cafeteria",
    serviceName: "Cafeteria",
    collegeId: "college-default-001",
    ratings: { quality: 4, variety: 3, cleanliness: 4, value: 3 },
    overallSatisfaction: 4,
    comment: "Would appreciate more vegetarian options.",
    submittedAt: getRecentTimestamp(1, 12),
  },
  {
    _id: "fb007",
    studentId: "STU2024156",
    studentName: "Grace Chen",
    serviceId: "library",
    serviceName: "Library",
    collegeId: "college-default-001",
    ratings: { resources: 4, environment: 5, staff: 5, hours: 4 },
    overallSatisfaction: 4,
    comment: "Staff is very helpful. Extended hours during exams would be great.",
    submittedAt: getRecentTimestamp(2, 1),
  },
  {
    _id: "fb008",
    studentId: "STU2024201",
    studentName: "Henry Brown",
    serviceId: "online-course",
    serviceName: "Online Course Portal",
    collegeId: "college-default-001",
    ratings: { usability: 4, content: 5, support: 4, reliability: 3 },
    overallSatisfaction: 4,
    comment: "Course content is excellent, minor technical issues.",
    submittedAt: getRecentTimestamp(2, 4),
  },
  {
    _id: "fb009",
    studentId: "STU2024234",
    studentName: "Ivy Taylor",
    serviceId: "hostel",
    serviceName: "Hostel",
    collegeId: "college-default-001",
    ratings: { cleanliness: 3, amenities: 3, security: 4, maintenance: 3 },
    overallSatisfaction: 3,
    comment: "Maintenance requests take too long to resolve.",
    submittedAt: getRecentTimestamp(2, 9),
  },
  {
    _id: "fb010",
    studentId: "STU2024267",
    studentName: "Jack Anderson",
    serviceId: "campus-event",
    serviceName: "Campus Events",
    collegeId: "college-default-001",
    ratings: { variety: 4, organization: 4, communication: 5, timing: 5 },
    overallSatisfaction: 4,
    comment: "Good events but could use more weekend activities.",
    submittedAt: getRecentTimestamp(3, 2),
  },
  {
    _id: "fb011",
    studentId: "STU2024312",
    studentName: "Kelly White",
    serviceId: "cafeteria",
    serviceName: "Cafeteria",
    collegeId: "college-default-001",
    ratings: { quality: 3, variety: 4, cleanliness: 4, value: 2 },
    overallSatisfaction: 3,
    comment: "Prices have gone up but quality hasn't improved.",
    submittedAt: getRecentTimestamp(3, 7),
  },
  {
    _id: "fb012",
    studentId: "STU2024345",
    studentName: "Leo Garcia",
    serviceId: "library",
    serviceName: "Library",
    collegeId: "college-default-001",
    ratings: { resources: 5, environment: 4, staff: 4, hours: 3 },
    overallSatisfaction: 4,
    comment: "Need more power outlets in study areas.",
    submittedAt: getRecentTimestamp(4, 3),
  },
];

// Advanced Analytics Mock Data
export const MOCK_ADVANCED_ANALYTICS: AdvancedAnalytics = {
  peakHours: [
    { hour: 8, label: "8AM", count: 12 },
    { hour: 9, label: "9AM", count: 28 },
    { hour: 10, label: "10AM", count: 45 },
    { hour: 11, label: "11AM", count: 52 },
    { hour: 12, label: "12PM", count: 38 },
    { hour: 13, label: "1PM", count: 32 },
    { hour: 14, label: "2PM", count: 48 },
    { hour: 15, label: "3PM", count: 55 },
    { hour: 16, label: "4PM", count: 42 },
    { hour: 17, label: "5PM", count: 35 },
    { hour: 18, label: "6PM", count: 25 },
    { hour: 19, label: "7PM", count: 18 },
  ],
  sentiment: {
    positive: 792,
    neutral: 312,
    negative: 143,
  },
  monthlyComparison: [
    { month: "Jan", thisYear: 85, lastYear: 72 },
    { month: "Feb", thisYear: 92, lastYear: 78 },
    { month: "Mar", thisYear: 108, lastYear: 95 },
    { month: "Apr", thisYear: 124, lastYear: 88 },
    { month: "May", thisYear: 156, lastYear: 112 },
    { month: "Jun", thisYear: 142, lastYear: 98 },
  ],
  serviceDetails: [
    {
      serviceId: "cafeteria",
      serviceName: "Cafeteria",
      responseRate: 78,
      avgResponseTime: 2.3,
      questionRatings: [
        { questionId: "food_quality", questionLabel: "Food Quality", avgRating: 4.2, responseCount: 312 },
        { questionId: "hygiene", questionLabel: "Hygiene", avgRating: 4.5, responseCount: 298 },
        { questionId: "staff_behavior", questionLabel: "Staff Behavior", avgRating: 4.0, responseCount: 285 },
      ],
    },
    {
      serviceId: "library",
      serviceName: "Library",
      responseRate: 82,
      avgResponseTime: 1.8,
      questionRatings: [
        { questionId: "book_availability", questionLabel: "Book Availability", avgRating: 4.6, responseCount: 289 },
        { questionId: "quietness", questionLabel: "Quietness", avgRating: 4.8, responseCount: 276 },
        { questionId: "seating_space", questionLabel: "Seating Space", avgRating: 4.3, responseCount: 265 },
      ],
    },
  ],
  topIssues: [
    "WiFi connectivity in hostel areas",
    "Online course platform stability",
    "Cafeteria pricing concerns",
    "Library seating during exam periods",
    "Event communication timing",
  ],
  improvementAreas: [
    { area: "WiFi Connectivity", score: 2.8, change: -0.3 },
    { area: "Platform Stability", score: 3.2, change: 0.2 },
    { area: "Food Pricing", score: 3.4, change: -0.1 },
    { area: "Maintenance Response", score: 3.5, change: 0.4 },
    { area: "Seating Availability", score: 3.8, change: 0.1 },
    { area: "Event Communication", score: 4.0, change: 0.5 },
  ],
};

// Flag to use mock data (set to false to use MongoDB)
// Set this to false when MongoDB is connected and you want real data
export const USE_MOCK_DATA = process.env.NEXT_PUBLIC_USE_MOCK_DATA !== 'false';

// Default users for easy testing
export const DEFAULT_USERS = {
  admin: {
    id: "ADMIN001",
    name: "Campus Admin",
    password: "admin123",
    role: "admin" as const,
  },
  student: {
    id: "STU2024001",
    name: "John Student",
    password: "student123",
    role: "student" as const,
  },
};

// Enhanced Dashboard Mock Data with Issue Detection and New Features
export const MOCK_DETECTED_ISSUES: DetectedIssue[] = [
  {
    id: "ISS001",
    title: "Hostel WiFi satisfaction dropped significantly",
    description: "WiFi connectivity satisfaction decreased by 35% in hostel areas over the past week",
    serviceId: "hostel",
    serviceName: "Hostel",
    servicesAffected: ["Hostel"],
    category: "infrastructure",
    severity: "critical",
    status: "investigating",
    detectedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    currentValue: 2.4,
    previousValue: 3.7,
    changePercent: -35.1,
    priority: 9,
    timeline: [],
    relatedFeedbackCount: 45,
    daysSinceDetection: 2,
    isOverdue: false,
    comments: [],
  },
  {
    id: "ISS002",
    title: "Cafeteria waiting time complaints increasing",
    description: "Multiple complaints about long waiting times during lunch hours",
    serviceId: "cafeteria",
    serviceName: "Cafeteria",
    servicesAffected: ["Cafeteria"],
    category: "service_quality",
    severity: "high",
    status: "open",
    detectedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    currentValue: 3.1,
    previousValue: 3.8,
    changePercent: -18.4,
    priority: 7,
    timeline: [],
    relatedFeedbackCount: 28,
    daysSinceDetection: 1,
    isOverdue: false,
    comments: [],
  },
  {
    id: "ISS003",
    title: "Library seating availability below threshold",
    description: "Seating space satisfaction dropped below 3.5 during exam period",
    serviceId: "library",
    serviceName: "Library",
    servicesAffected: ["Library"],
    category: "accessibility",
    severity: "medium",
    status: "investigating",
    detectedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    currentValue: 3.3,
    previousValue: 4.1,
    changePercent: -19.5,
    priority: 6,
    timeline: [],
    relatedFeedbackCount: 22,
    daysSinceDetection: 3,
    isOverdue: false,
    comments: [],
  },
  {
    id: "ISS004",
    title: "Online course platform slow during peak hours",
    description: "Platform usability ratings declining, multiple reports of slowness",
    serviceId: "online-course",
    serviceName: "Online Course Portal",
    servicesAffected: ["Online Course"],
    category: "infrastructure",
    severity: "high",
    status: "open",
    detectedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    currentValue: 3.2,
    previousValue: 3.9,
    changePercent: -17.9,
    priority: 8,
    timeline: [],
    relatedFeedbackCount: 31,
    daysSinceDetection: 0,
    isOverdue: false,
    comments: [],
  },
  {
    id: "ISS005",
    title: "Cafeteria menu variety concerns",
    description: "Decreasing satisfaction with menu variety and vegetarian options",
    serviceId: "cafeteria",
    serviceName: "Cafeteria",
    servicesAffected: ["Cafeteria"],
    category: "service_quality",
    severity: "medium",
    status: "open",
    detectedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    currentValue: 3.4,
    previousValue: 3.9,
    changePercent: -12.8,
    priority: 5,
    timeline: [],
    relatedFeedbackCount: 19,
    daysSinceDetection: 5,
    isOverdue: false,
    comments: [],
  },
];

export const MOCK_SERVICE_RANKINGS: ServiceRanking[] = [
  {
    rank: 1,
    serviceId: "library",
    serviceName: "Library",
    score: 4.7,
    change: 0.2,
    trend: "up",
    departmentName: SERVICE_TO_DEPARTMENT_MAP["library"],
  },
  {
    rank: 2,
    serviceId: "campus-event",
    serviceName: "Campus Events",
    score: 4.5,
    change: 0.3,
    trend: "up",
    departmentName: SERVICE_TO_DEPARTMENT_MAP["campus-event"],
  },
  {
    rank: 3,
    serviceId: "cafeteria",
    serviceName: "Cafeteria",
    score: 4.2,
    change: -0.1,
    trend: "down",
    departmentName: SERVICE_TO_DEPARTMENT_MAP["cafeteria"],
  },
  {
    rank: 4,
    serviceId: "hostel",
    serviceName: "Hostel",
    score: 3.9,
    change: -0.3,
    trend: "down",
    departmentName: SERVICE_TO_DEPARTMENT_MAP["hostel"],
  },
  {
    rank: 5,
    serviceId: "online-course",
    serviceName: "Online Course Portal",
    score: 3.8,
    change: 0.0,
    trend: "stable",
    departmentName: SERVICE_TO_DEPARTMENT_MAP["online-course"],
  },
];

export const MOCK_PARTICIPATION: ParticipationMetrics = {
  totalStudents: TOTAL_ENROLLED_STUDENTS,
  totalResponses: 1247,
  participationRate: 16.8, // (420 unique / 2500) * 100
  uniqueRespondents: 420,
  averageResponsesPerStudent: 2.97, // 1247 / 420
};

export const MOCK_TOP_COMPLAINTS: ComplaintSummary[] = [
  {
    issue: "WiFi connectivity issues",
    count: 87,
    services: ["Hostel", "Library"],
    severity: "critical",
    trend: "increasing",
  },
  {
    issue: "Long waiting times",
    count: 64,
    services: ["Cafeteria"],
    severity: "high",
    trend: "increasing",
  },
  {
    issue: "Platform performance during peak hours",
    count: 52,
    services: ["Online Course Portal"],
    severity: "high",
    trend: "stable",
  },
  {
    issue: "Limited seating availability",
    count: 48,
    services: ["Library", "Cafeteria"],
    severity: "medium",
    trend: "increasing",
  },
  {
    issue: "Menu variety and options",
    count: 41,
    services: ["Cafeteria"],
    severity: "medium",
    trend: "stable",
  },
  {
    issue: "Maintenance response time",
    count: 35,
    services: ["Hostel"],
    severity: "medium",
    trend: "decreasing",
  },
  {
    issue: "Extended hours needed",
    count: 28,
    services: ["Library"],
    severity: "low",
    trend: "stable",
  },
];

export const MOCK_DEPARTMENT_PERFORMANCE: DepartmentPerformance[] = [
  {
    departmentId: "academic-resources",
    departmentName: "Academic Resources",
    avgScore: 4.7,
    totalFeedback: 289,
    trend: "up",
    serviceCounts: 1,
  },
  {
    departmentId: "student-affairs",
    departmentName: "Student Affairs",
    avgScore: 4.5,
    totalFeedback: 203,
    trend: "up",
    serviceCounts: 1,
  },
  {
    departmentId: "food-services",
    departmentName: "Food Services",
    avgScore: 4.2,
    totalFeedback: 312,
    trend: "down",
    serviceCounts: 1,
  },
  {
    departmentId: "residential-management",
    departmentName: "Residential Management",
    avgScore: 3.9,
    totalFeedback: 198,
    trend: "down",
    serviceCounts: 1,
  },
  {
    departmentId: "academic-technology",
    departmentName: "Academic Technology",
    avgScore: 3.8,
    totalFeedback: 245,
    trend: "stable",
    serviceCounts: 1,
  },
];

// ========== OPERATIONAL FEATURES MOCK DATA ==========

export const MOCK_MANAGED_ISSUES: ManagedIssue[] = [
  {
    id: "issue-001",
    title: "Cafeteria Wait Times Excessive",
    description: "Students reporting 30+ minute waits during lunch hours. Multiple complaints about food running out.",
    serviceId: "cafeteria",
    serviceName: "Cafeteria",
    servicesAffected: ["Cafeteria"],
    category: "service_quality",
    severity: "high",
    status: "investigating",
    detectedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    currentValue: 4.2,
    previousValue: 4.5,
    changePercent: -6.7,
    priority: 8,
    assignedToName: "Dr. Sarah Johnson",
    assignedToEmail: "s.johnson@college.edu",
    assignedToRole: "Food Services Manager",
    expectedResolution: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    slaStatus: "on-time",
    slaHoursRemaining: 168, // 7 days * 24 hours
    serviceOwnerId: "owner-001",
    actions: [
      {
        id: "action-001",
        issueId: "issue-001",
        action: "Conducted time-motion study",
        takenBy: "Operations Team",
        takenByRole: "Operations Analyst",
        timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        notes: "Peak waiting time confirmed at 35 minutes. Bottleneck identified at payment counter.",
        actionType: "comment",
      },
      {
        id: "action-002",
        issueId: "issue-001",
        action: "Met with cafeteria management",
        takenBy: "Dr. Sarah Johnson",
        takenByRole: "Food Services Manager",
        timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        notes: "Discussed adding second payment counter and increasing staff during peak hours.",
        actionType: "status_change",
      },
    ],
    timeline: [],
    relatedFeedbackCount: 32,
    daysSinceDetection: 7,
    isOverdue: false,
    comments: [],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "issue-002",
    title: "Library HVAC System Failure",
    description: "Temperature control issues causing discomfort in study areas.",
    serviceId: "library",
    serviceName: "Library",
    servicesAffected: ["Library"],
    category: "infrastructure",
    severity: "medium",
    status: "investigating",
    detectedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    currentValue: 4.7,
    previousValue: 4.9,
    changePercent: -4.1,
    priority: 5,
    assignedToName: "Mike Thompson",
    assignedToEmail: "m.thompson@college.edu",
    assignedToRole: "Facilities Manager",
    expectedResolution: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    slaStatus: "on-time",
    slaHoursRemaining: 72, // 3 days * 24 hours
    serviceOwnerId: "owner-002",
    actions: [
      {
        id: "action-003",
        issueId: "issue-002",
        action: "HVAC inspection completed",
        takenBy: "Facilities Team",
        takenByRole: "Technician",
        timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        notes: "Identified faulty thermostat on second floor.",
        actionType: "comment",
      },
      {
        id: "action-004",
        issueId: "issue-002",
        action: "Ordered replacement parts",
        takenBy: "Procurement",
        takenByRole: "Procurement Officer",
        timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        notes: "Parts arriving this week. Installation scheduled.",
        actionType: "comment",
      },
    ],
    timeline: [],
    relatedFeedbackCount: 18,
    daysSinceDetection: 14,
    isOverdue: false,
    comments: [],
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "issue-003",
    title: "Online Portal Login Issues",
    description: "Students reporting frequent authentication failures and timeout errors.",
    serviceId: "online-course",
    serviceName: "Online Course Portal",
    servicesAffected: ["Online Course Portal"],
    category: "infrastructure",
    severity: "critical",
    status: "open",
    detectedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    currentValue: 3.8,
    previousValue: 4.1,
    changePercent: -7.3,
    priority: 10,
    assignedToName: "James Rodriguez",
    assignedToEmail: "j.rodriguez@college.edu",
    assignedToRole: "IT Director",
    expectedResolution: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day
    slaStatus: "at-risk", // Less than 48 hours remaining
    slaHoursRemaining: 24,
    serviceOwnerId: "owner-003",
    actions: [
      {
        id: "action-005",
        issueId: "issue-003",
        action: "Issue reported to IT team",
        takenBy: "Student Services",
        takenByRole: "Support Staff",
        timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        notes: "High priority - affecting multiple classes.",
        actionType: "assignment",
      },
    ],
    timeline: [],
    relatedFeedbackCount: 27,
    daysSinceDetection: 2,
    isOverdue: false,
    comments: [],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "issue-004",
    title: "Hostel Internet Bandwidth Insufficient",
    description: "Slow internet speeds during evening hours preventing students from completing online coursework.",
    serviceId: "hostel",
    serviceName: "Hostel",
    servicesAffected: ["Hostel"],
    category: "infrastructure",
    severity: "critical",
    status: "resolved",
    detectedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    currentValue: 4.5,
    previousValue: 3.2,
    changePercent: 40.6,
    priority: 9,
    assignedToName: "Lisa Chen",
    assignedToEmail: "l.chen@college.edu",
    assignedToRole: "Network Administrator",
    serviceOwnerId: "owner-004",
    improvementVerified: true,
    verificationDetails: {
      beforeScore: 3.2,
      afterScore: 4.5,
      improvementPercent: 40.6,
      verifiedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      verifiedBy: "System - Automated",
    },
    actions: [
      {
        id: "action-006",
        issueId: "issue-004",
        action: "Network capacity analysis",
        takenBy: "IT Team",
        takenByRole: "Network Engineer",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        notes: "Current bandwidth insufficient for increased usage.",
        actionType: "comment",
      },
      {
        id: "action-007",
        issueId: "issue-004",
        action: "Bandwidth upgrade approved",
        takenBy: "James Rodriguez",
        takenByRole: "IT Director",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        notes: "Doubling bandwidth from 500 Mbps to 1 Gbps.",
        actionType: "status_change",
      },
      {
        id: "action-008",
        issueId: "issue-004",
        action: "Infrastructure upgrade completed",
        takenBy: "Network Team",
        takenByRole: "Network Engineer",
        timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        notes: "New fiber lines installed. Testing in progress.",
        actionType: "comment",
      },
    ],
    resolution: {
      resolvedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      resolvedBy: "Lisa Chen",
      resolutionNotes: "Bandwidth upgraded from 500 Mbps to 1 Gbps. Added network monitoring to prevent future issues. Student satisfaction increased from 3.2 to 4.5.",
      satisfactionBefore: 3.2,
      satisfactionAfter: 4.5,
      verificationPeriodDays: 7,
      isVerified: true,
      verifiedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      improvementPercent: 40.6,
    },
    timeline: [],
    relatedFeedbackCount: 21,
    daysSinceDetection: 30,
    isOverdue: false,
    comments: [],
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Service Owners Mock Data
export const MOCK_SERVICE_OWNERS: ServiceOwner[] = [
  {
    id: "owner-001",
    serviceId: "cafeteria",
    serviceName: "Cafeteria",
    departmentName: "Food Services",
    ownerName: "Dr. Sarah Johnson",
    ownerTitle: "Food Services Manager",
    ownerEmail: "s.johnson@college.edu",
    ownerPhone: "+1 (555) 0101",
    collegeId: "college-default-001",
    assignedIssues: 2,
    resolvedIssues: 8,
    avgResolutionTime: 96, // hours
    serviceHealthScore: 4.2,
  },
  {
    id: "owner-002",
    serviceId: "library",
    serviceName: "Library",
    departmentName: "Academic Resources",
    ownerName: "Prof. Michael Thompson",
    ownerTitle: "Library Director",
    ownerEmail: "m.thompson@college.edu",
    ownerPhone: "+1 (555) 0102",
    collegeId: "college-default-001",
    assignedIssues: 1,
    resolvedIssues: 12,
    avgResolutionTime: 72,
    serviceHealthScore: 4.8,
  },
  {
    id: "owner-003",
    serviceId: "online-course",
    serviceName: "Online Course Portal",
    departmentName: "Information Technology",
    ownerName: "James Rodriguez",
    ownerTitle: "IT Director",
    ownerEmail: "j.rodriguez@college.edu",
    ownerPhone: "+1 (555) 0103",
    collegeId: "college-default-001",
    assignedIssues: 3,
    resolvedIssues: 15,
    avgResolutionTime: 48,
    serviceHealthScore: 4.1,
  },
  {
    id: "owner-004",
    serviceId: "hostel",
    serviceName: "Hostel",
    departmentName: "Residential Services",
    ownerName: "Lisa Chen",
    ownerTitle: "Residential Director",
    ownerEmail: "l.chen@college.edu",
    ownerPhone: "+1 (555) 0104",
    collegeId: "college-default-001",
    assignedIssues: 1,
    resolvedIssues: 10,
    avgResolutionTime: 120,
    serviceHealthScore: 4.3,
  },
  {
    id: "owner-005",
    serviceId: "campus-event",
    serviceName: "Campus Events",
    departmentName: "Student Affairs",
    ownerName: "David Martinez",
    ownerTitle: "Student Activities Coordinator",
    ownerEmail: "d.martinez@college.edu",
    ownerPhone: "+1 (555) 0105",
    collegeId: "college-default-001",
    assignedIssues: 0,
    resolvedIssues: 5,
    avgResolutionTime: 60,
    serviceHealthScore: 4.6,
  },
];

export const MOCK_AI_INSIGHTS: AIInsight[] = [
  {
    id: "ai-insight-001",
    collegeId: "college-default-001",
    type: "trend",
    title: "Library Satisfaction Trending Up",
    description: "Library satisfaction has increased by 18% over the past month, driven by extended hours and new study spaces. This positive trend is consistent across all time periods.",
    priority: "low",
    affectedServices: ["Library"],
    confidence: 0.92,
    generatedAt: new Date().toISOString(),
    actionable: false,
  },
  {
    id: "ai-insight-002",
    collegeId: "college-default-001",
    type: "anomaly",
    title: "Cafeteria Ratings Drop on Mondays",
    description: "Cafeteria satisfaction scores are consistently 15-20% lower on Mondays compared to other weekdays. Analysis suggests menu variety and food quality concerns.",
    priority: "high",
    affectedServices: ["Cafeteria"],
    confidence: 0.87,
    generatedAt: new Date().toISOString(),
    actionable: true,
    suggestedAction: "Review Monday menu planning and consider increasing variety. Investigate food preparation timing for Monday morning deliveries.",
    status: "new",
  },
  {
    id: "ai-insight-003",
    collegeId: "college-default-001",
    type: "recommendation",
    title: "Replicate Library Success to Online Portal",
    description: "The recent improvements in Library services (extended hours, better facilities) have driven satisfaction from 4.2 to 4.7. Similar user-centric improvements could benefit the Online Course Portal.",
    priority: "medium",
    affectedServices: ["Online Course Portal", "Library"],
    confidence: 0.78,
    generatedAt: new Date().toISOString(),
    actionable: true,
    suggestedAction: "Conduct user experience study for Online Portal. Implement UI improvements and increase technical support availability.",
    status: "acknowledged",
  },
  {
    id: "ai-insight-004",
    collegeId: "college-default-001",
    type: "anomaly",
    title: "Sharp Decline in Hostel Satisfaction After 10 PM",
    description: "Survey responses submitted after 10 PM show 35% lower satisfaction scores for hostel services, primarily citing noise complaints and internet issues during peak study hours.",
    priority: "high",
    affectedServices: ["Hostel"],
    confidence: 0.84,
    generatedAt: new Date().toISOString(),
    actionable: true,
    suggestedAction: "Implement quiet hours policy enforcement. Upgrade network infrastructure to handle evening peak load. Consider creating designated study lounges.",
    status: "acted_upon",
  },
  {
    id: "ai-insight-005",
    collegeId: "college-default-001",
    type: "summary",
    title: "Overall Campus Satisfaction Stable at 4.2",
    description: "Campus-wide satisfaction has remained steady at 4.2/5 for the past three months. While stable, this represents an opportunity for targeted improvements in underperforming areas.",
    priority: "low",
    affectedServices: ["Cafeteria", "Library", "Online Course Portal", "Hostel", "Campus Events"],
    confidence: 0.95,
    generatedAt: new Date().toISOString(),
    actionable: false,
    status: "new",
  },
];

export const MOCK_WEEKLY_SUMMARY: WeeklySummary = {
  id: "weekly-summary-001",
  collegeId: "college-default-001",
  weekStart: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  weekEnd: new Date().toISOString(),
  totalFeedback: 1247,
  avgSatisfaction: 4.2,
  satisfactionChange: 0.2, // vs previous week (numeric value)
  lowestService: {
    name: "Online Course Portal",
    score: 3.8,
  },
  highestService: {
    name: "Library",
    score: 4.7,
  },
  topComplaint: "Cafeteria wait times excessive during lunch hours",
  newIssues: 2,
  resolvedIssues: 1,
  participationRate: 45.2,
  trend: "improving",
  keyInsights: [
    "Library extended hours initiative driving 18% satisfaction increase",
    "Online Portal experiencing critical authentication issues - IT team actively resolving",
    "Cafeteria wait times peak at 35 minutes during lunch - process improvements in progress",
    "Hostel internet bandwidth upgrade completed, satisfaction improved from 3.2 to 4.5",
    "Campus Events receiving positive feedback, consistently above 4.5/5",
  ],
  recommendations: [
    "Prioritize Online Course Portal stability - consider load balancing and infrastructure review",
    "Implement second payment counter in cafeteria to reduce wait times",
    "Expand library success model (extended hours, better facilities) to other services",
    "Conduct quarterly service owner review meetings to maintain accountability",
    "Consider creating student advisory panel for continuous feedback on improvement initiatives",
  ],
  generatedAt: new Date().toISOString(),
  generatedBy: "ai",
};

export const MOCK_SERVICE_HEALTH: ServiceHealth[] = [
  {
    serviceId: "library",
    serviceName: "Library",
    status: "excellent",
    score: 4.7,
    participationRate: 45.2,
    issueCount: 0,
    trend: "up",
    message: "All metrics performing exceptionally well",
  },
  {
    serviceId: "campus-event",
    serviceName: "Campus Events",
    status: "excellent",
    score: 4.5,
    participationRate: 31.8,
    issueCount: 0,
    trend: "stable",
    message: "Consistently high satisfaction",
  },
  {
    serviceId: "cafeteria",
    serviceName: "Cafeteria",
    status: "good",
    score: 4.2,
    participationRate: 48.9,
    issueCount: 1,
    trend: "down",
    message: "One active issue requiring attention",
  },
  {
    serviceId: "hostel",
    serviceName: "Hostel",
    status: "warning",
    score: 3.9,
    participationRate: 29.4,
    issueCount: 1,
    trend: "up",
    message: "Recent improvements showing positive impact",
  },
  {
    serviceId: "online-course",
    serviceName: "Online Course Portal",
    status: "critical",
    score: 3.8,
    participationRate: 38.5,
    issueCount: 2,
    trend: "down",
    message: "Critical technical issues affecting user experience",
  },
];

export const MOCK_PARTICIPATION_BY_SERVICE: ServiceParticipation[] = [
  {
    serviceId: "cafeteria",
    serviceName: "Cafeteria",
    totalResponses: 312,
    expectedResponses: 638,
    participationRate: 48.9,
    trend: "increasing",
    reliability: "high",
  },
  {
    serviceId: "library",
    serviceName: "Library",
    totalResponses: 289,
    expectedResponses: 640,
    participationRate: 45.2,
    trend: "stable",
    reliability: "high",
  },
  {
    serviceId: "online-course",
    serviceName: "Online Course Portal",
    totalResponses: 245,
    expectedResponses: 637,
    participationRate: 38.5,
    trend: "increasing",
    reliability: "medium",
  },
  {
    serviceId: "campus-event",
    serviceName: "Campus Events",
    totalResponses: 203,
    expectedResponses: 638,
    participationRate: 31.8,
    trend: "stable",
    reliability: "medium",
  },
  {
    serviceId: "hostel",
    serviceName: "Hostel",
    totalResponses: 198,
    expectedResponses: 674,
    participationRate: 29.4,
    trend: "decreasing",
    reliability: "medium",
  },
];

export const MOCK_HISTORICAL_COMPARISON: HistoricalComparison = {
  currentPeriod: {
    label: "Current Month",
    startDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date().toISOString(),
    avgSatisfaction: 4.2,
    totalFeedback: 1247,
    topIssue: "Cafeteria Wait Times Excessive",
  },
  previousPeriod: {
    label: "Previous Month",
    startDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    avgSatisfaction: 4.0,
    totalFeedback: 1102,
    topIssue: "Library HVAC System Failure",
  },
  changePercent: 5.0,
  trend: "improving",
  insights: [
    "Satisfaction improved by 0.2 points compared to last month.",
    "Feedback volume increased by 13%.",
    "Cafeteria wait times are the top concern this month.",
  ],
  significantChanges: [
    {
      service: "Library",
      currentValue: 4.7,
      previousValue: 4.2,
      changePercent: 11.9,
      changeDirection: "improvement",
    },
    {
      service: "Online Course Portal",
      currentValue: 3.8,
      previousValue: 4.1,
      changePercent: -7.3,
      changeDirection: "decline",
    },
    {
      service: "Hostel",
      currentValue: 3.9,
      previousValue: 3.2,
      changePercent: 21.9,
      changeDirection: "improvement",
    },
    {
      service: "Cafeteria",
      currentValue: 4.2,
      previousValue: 4.1,
      changePercent: 2.4,
      changeDirection: "stable",
    },
  ],
};

export const MOCK_STUDENT_VOICE: AggregatedStudentVoice = {
  representativeComments: [
    {
      text: "The new extended library hours are a game-changer! I can finally study late without worrying about closing time.",
      service: "Library",
      sentiment: "positive",
      rating: 5,
      date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    },
    {
      text: "Cafeteria wait times are still too long during lunch. I've had to skip meals because I couldn't wait 30+ minutes.",
      service: "Cafeteria",
      sentiment: "negative",
      rating: 2,
      date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    },
    {
      text: "The online portal keeps timing out during assignment submissions. Really stressful when deadlines are approaching.",
      service: "Online Course Portal",
      sentiment: "negative",
      rating: 2,
      date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    },
    {
      text: "Great improvement in hostel internet speed! I can actually attend my online classes without lag now.",
      service: "Hostel",
      sentiment: "positive",
      rating: 5,
      date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    },
    {
      text: "Campus events have been really engaging this semester. Love the variety and the effort put into organizing them.",
      service: "Campus Events",
      sentiment: "positive",
      rating: 5,
      date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    },
    {
      text: "Food quality in the cafeteria is decent, but more vegetarian options would be appreciated.",
      service: "Cafeteria",
      sentiment: "neutral",
      rating: 3,
      date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    },
  ],
  commonPhrases: [
    "extended hours",
    "wait times",
    "technical issues",
    "internet speed",
    "food quality",
    "more options",
    "study spaces",
    "authentication problems",
  ],
  sentimentBreakdown: {
    positive: 50,
    neutral: 20,
    negative: 30,
  },
};

export const MOCK_ENHANCED_DASHBOARD: EnhancedDashboard = {
  ...MOCK_ANALYTICS,
  detectedIssues: MOCK_DETECTED_ISSUES,
  serviceRankings: MOCK_SERVICE_RANKINGS,
  participation: MOCK_PARTICIPATION,
  topComplaints: MOCK_TOP_COMPLAINTS,
  departmentPerformance: MOCK_DEPARTMENT_PERFORMANCE,
  // Operational features
  managedIssues: MOCK_MANAGED_ISSUES,
  aiInsights: MOCK_AI_INSIGHTS,
  weeklySummary: MOCK_WEEKLY_SUMMARY,
  serviceHealth: MOCK_SERVICE_HEALTH,
  participationByService: MOCK_PARTICIPATION_BY_SERVICE,
  historicalComparison: MOCK_HISTORICAL_COMPARISON,
  studentVoice: MOCK_STUDENT_VOICE,
};

// ==================== NEW OPERATIONAL MOCK DATA ====================

// Mock Alerts
export const MOCK_ALERTS: Alert[] = [
  {
    id: "alert-001",
    type: "satisfaction_drop",
    severity: "critical",
    status: "active",
    title: "Critical Satisfaction Drop in Hostel Services",
    message: "Hostel satisfaction has dropped to 2.4, falling below the critical threshold of 2.5. Immediate attention required.",
    serviceId: "hostel",
    serviceName: "Hostel",
    thresholdValue: 2.5,
    currentValue: 2.4,
    recipients: ["admin-001", "dept-mgr-003"],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    actionUrl: "/dashboard?service=hostel",
    recommendedActions: [
      "Review recent WiFi stability complaints",
      "Schedule emergency meeting with hostel management",
      "Send survey to affected students to identify specific issues",
    ],
    collegeId: "college-001",
  },
  {
    id: "alert-002",
    type: "deadline_missed",
    severity: "high",
    status: "active",
    title: "Cafeteria Issue Resolution Overdue",
    message: "Issue #ISS-102 regarding cafeteria food quality was expected to be resolved 2 days ago.",
    issueId: "ISS-102",
    serviceId: "cafeteria",
    serviceName: "Cafeteria",
    recipients: ["admin-001", "dept-mgr-001"],
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    actionUrl: "/dashboard?issue=ISS-102",
    recommendedActions: [
      "Escalate to department head",
      "Request status update from assigned staff",
      "Consider interim solutions",
    ],
    collegeId: "college-001",
  },
  {
    id: "alert-003",
    type: "low_participation",
    severity: "medium",
    status: "acknowledged",
    title: "Low Response Rate for Campus Events",
    message: "Campus events feedback participation is only 11%, below the target of 30%.",
    serviceId: "campus-event",
    serviceName: "Campus Events",
    thresholdValue: 30,
    currentValue: 11,
    recipients: ["admin-001"],
    acknowledgedBy: "admin-001",
    acknowledgedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    actionUrl: "/dashboard?service=campus-event",
    recommendedActions: [
      "Send targeted reminder emails to students",
      "Add QR code feedback collection at event venues",
      "Offer small incentives for feedback participation",
    ],
    collegeId: "college-001",
  },
];

// Mock Student Segmentation
export const MOCK_SEGMENTED_ANALYTICS: SegmentedAnalytics = {
  byYear: [
    {
      segmentType: "year",
      segmentValue: "1",
      segmentLabel: "Year 1",
      totalStudents: 650,
      totalResponses: 298,
      participationRate: 45.8,
      avgSatisfaction: 3.8,
      topService: "Library",
      topIssue: "Hostel WiFi connectivity",
    },
    {
      segmentType: "year",
      segmentValue: "2",
      segmentLabel: "Year 2",
      totalStudents: 620,
      totalResponses: 310,
      participationRate: 50.0,
      avgSatisfaction: 4.1,
      topService: "Library",
    },
    {
      segmentType: "year",
      segmentValue: "3",
      segmentLabel: "Year 3",
      totalStudents: 580,
      totalResponses: 285,
      participationRate: 49.1,
      avgSatisfaction: 4.3,
      topService: "Online Course",
    },
    {
      segmentType: "year",
      segmentValue: "4",
      segmentLabel: "Year 4",
      totalStudents: 650,
      totalResponses: 260,
      participationRate: 40.0,
      avgSatisfaction: 4.2,
      topService: "Library",
    },
  ],
  byDepartment: [
    {
      segmentType: "department",
      segmentValue: "cs",
      segmentLabel: "Computer Science",
      totalStudents: 580,
      totalResponses: 315,
      participationRate: 54.3,
      avgSatisfaction: 4.3,
      topService: "Online Course",
    },
    {
      segmentType: "department",
      segmentValue: "ee",
      segmentLabel: "Electrical Engineering",
      totalStudents: 520,
      totalResponses: 245,
      participationRate: 47.1,
      avgSatisfaction: 4.0,
      topService: "Library",
    },
    {
      segmentType: "department",
      segmentValue: "me",
      segmentLabel: "Mechanical Engineering",
      totalStudents: 490,
      totalResponses: 228,
      participationRate: 46.5,
      avgSatisfaction: 3.9,
      topService: "Cafeteria",
      topIssue: "Limited vegetarian options",
    },
    {
      segmentType: "department",
      segmentValue: "ba",
      segmentLabel: "Business Administration",
      totalStudents: 410,
      totalResponses: 195,
      participationRate: 47.6,
      avgSatisfaction: 4.2,
      topService: "Campus Events",
    },
  ],
  byResidence: [
    {
      segmentType: "residence",
      segmentValue: "hostel",
      segmentLabel: "Hostel Residents",
      totalStudents: 1450,
      totalResponses: 685,
      participationRate: 47.2,
      avgSatisfaction: 3.9,
      topService: "Hostel",
      topIssue: "WiFi connectivity issues",
    },
    {
      segmentType: "residence",
      segmentValue: "day_scholar",
      segmentLabel: "Day Scholars",
      totalStudents: 850,
      totalResponses: 425,
      participationRate: 50.0,
      avgSatisfaction: 4.4,
      topService: "Library",
    },
    {
      segmentType: "residence",
      segmentValue: "off_campus",
      segmentLabel: "Off-Campus",
      totalStudents: 200,
      totalResponses: 43,
      participationRate: 21.5,
      avgSatisfaction: 4.1,
      topService: "Online Course",
    },
  ],
  byProgram: [
    {
      segmentType: "program",
      segmentValue: "undergraduate",
      segmentLabel: "Undergraduate",
      totalStudents: 2100,
      totalResponses: 995,
      participationRate: 47.4,
      avgSatisfaction: 4.1,
      topService: "Library",
    },
    {
      segmentType: "program",
      segmentValue: "postgraduate",
      segmentLabel: "Postgraduate",
      totalStudents: 320,
      totalResponses: 148,
      participationRate: 46.3,
      avgSatisfaction: 4.3,
      topService: "Online Course",
    },
    {
      segmentType: "program",
      segmentValue: "doctoral",
      segmentLabel: "Doctoral",
      totalStudents: 80,
      totalResponses: 10,
      participationRate: 12.5,
      avgSatisfaction: 3.8,
      topService: "Library",
    },
  ],
  insights: [
    "Year 1 students report 20% lower hostel satisfaction (3.8 vs 4.1 overall), primarily due to WiFi connectivity issues",
    "Day scholars have the highest satisfaction (4.4) but hostel residents are 11% below average",
    "Computer Science department shows highest engagement (54.3% participation) and satisfaction (4.3)",
    "Doctoral students have critically low participation (12.5%) - targeted outreach needed",
  ],
};

// Mock Service Benchmarks
export const MOCK_SERVICE_BENCHMARKS: ServiceBenchmark[] = [
  {
    serviceId: "library",
    serviceName: "Library",
    collegeId: "college-001",
    currentScore: 4.6,
    currentParticipation: 52.3,
    currentIssueCount: 0,
    campusAverage: 4.1,
    performanceLabel: "excellent",
    vsAverage: 0.5,
    percentile: 95,
    trendVsLastPeriod: 0.1,
    lastUpdated: new Date().toISOString(),
  },
  {
    serviceId: "online-course",
    serviceName: "Online Course",
    collegeId: "college-001",
    currentScore: 4.4,
    currentParticipation: 48.1,
    currentIssueCount: 0,
    campusAverage: 4.1,
    performanceLabel: "above_average",
    vsAverage: 0.3,
    percentile: 75,
    trendVsLastPeriod: 0.2,
    lastUpdated: new Date().toISOString(),
  },
  {
    serviceId: "cafeteria",
    serviceName: "Cafeteria",
    collegeId: "college-001",
    currentScore: 3.9,
    currentParticipation: 45.2,
    currentIssueCount: 2,
    campusAverage: 4.1,
    performanceLabel: "below_average",
    vsAverage: -0.2,
    percentile: 40,
    trendVsLastPeriod: -0.1,
    lastUpdated: new Date().toISOString(),
  },
  {
    serviceId: "campus-event",
    serviceName: "Campus Events",
    collegeId: "college-001",
    currentScore: 4.1,
    currentParticipation: 11.2,
    currentIssueCount: 0,
    campusAverage: 4.1,
    performanceLabel: "average",
    vsAverage: 0.0,
    percentile: 50,
    trendVsLastPeriod: 0.0,
    lastUpdated: new Date().toISOString(),
  },
  {
    serviceId: "hostel",
    serviceName: "Hostel",
    collegeId: "college-001",
    currentScore: 2.4,
    currentParticipation: 47.3,
    currentIssueCount: 3,
    campusAverage: 4.1,
    performanceLabel: "needs_attention",
    vsAverage: -1.7,
    percentile: 5,
    trendVsLastPeriod: -0.4,
    lastUpdated: new Date().toISOString(),
  },
];

export const MOCK_BENCHMARK_SUMMARY: BenchmarkSummary = {
  totalServices: 5,
  aboveAverage: 2,
  belowAverage: 2,
  campusAverage: 4.1,
  topPerformingService: "Library",
  needsAttentionService: "Hostel",
  benchmarks: MOCK_SERVICE_BENCHMARKS,
};

// Mock Participation Insights
export const MOCK_PARTICIPATION_INSIGHTS: ParticipationInsight[] = [
  {
    type: "low_service",
    severity: "high",
    title: "Campus Events Participation Critically Low",
    description: "Campus Events service has only 11% participation rate, far below the campus average of 47%.",
    currentRate: 11.2,
    targetRate: 35.0,
    gap: 23.8,
    affectedService: "Campus Events",
    recommendations: [
      {
        action: "Add QR code feedback at event check-in",
        expectedImpact: "Increase participation by 15-20%",
        effort: "low",
        priority: 1,
      },
      {
        action: "Send automated feedback request within 24 hours of event",
        expectedImpact: "Increase participation by 10-15%",
        effort: "medium",
        priority: 2,
      },
      {
        action: "Offer event attendance points for feedback submission",
        expectedImpact: "Increase participation by 20-25%",
        effort: "high",
        priority: 3,
      },
    ],
    identifiedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new",
  },
  {
    type: "segment_gap",
    severity: "high",
    title: "Doctoral Students Not Participating",
    description: "Doctoral students have only 12.5% participation rate compared to 47% campus average.",
    currentRate: 12.5,
    targetRate: 35.0,
    gap: 22.5,
    affectedSegment: "Doctoral Students",
    recommendations: [
      {
        action: "Send personalized emails to doctoral students",
        expectedImpact: "Increase participation by 10-12%",
        effort: "low",
        priority: 1,
      },
      {
        action: "Schedule feedback collection during research seminars",
        expectedImpact: "Increase participation by 15-20%",
        effort: "medium",
        priority: 2,
      },
    ],
    identifiedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "in_progress",
  },
  {
    type: "declining_trend",
    severity: "medium", 
    title: "Participation Declining for Hostel Services",
    description: "Hostel service participation has dropped from 52% to 47% over the past month.",
    currentRate: 47.3,
    targetRate: 52.0,
    gap: 4.7,
    affectedService: "Hostel",
    recommendations: [
      {
        action: "Place feedback kiosks in hostel common areas",
        expectedImpact: "Increase participation by 5-8%",
        effort: "medium",
        priority: 1,
      },
    ],
    identifiedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new",
  },
];

// Mock Improvement Timelines
export const MOCK_IMPROVEMENT_TIMELINES: ImprovementTimeline[] = [
  {
    issueId: "ISS-098",
    issueTitle: "Cafeteria Food Quality Issues",
    serviceId: "cafeteria",
    serviceName: "Cafeteria",
    startDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    targetCompletionDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    actualCompletionDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    totalDays: 40,
    currentPhase: "verified",
    milestones: [
      {
        phase: "detected",
        completedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
        completedBy: "System",
        notes: "Automated detection triggered by satisfaction drop below 3.5",
        metrics: { satisfactionScore: 3.2, complaintCount: 45 },
      },
      {
        phase: "investigating",
        completedAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
        completedBy: "Food Services Manager",
        notes: "Root cause identified: supplier changed ingredients without notice",
      },
      {
        phase: "implementing",
        completedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        completedBy: "Food Services Manager",
        notes: "Switched to premium supplier, added student feedback board",
      },
      {
        phase: "measuring",
        completedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        completedBy: "System",
        notes: "Measuring satisfaction over 2-week period",
        metrics: { satisfactionScore: 4.2, complaintCount: 8 },
      },
      {
        phase: "verified",
        completedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        completedBy: "College Admin",
        notes: "Improvement verified - satisfaction increased by 31%",
        metrics: { satisfactionScore: 4.2, complaintCount: 8 },
      },
    ],
    initialMetrics: {
      satisfactionScore: 3.2,
      complaintCount: 45,
      participationRate: 42.5,
      measurementDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    },
    finalMetrics: {
      satisfactionScore: 4.2,
      complaintCount: 8,
      participationRate: 45.2,
      measurementDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    improvementPercent: 31.3,
    isSuccessful: true,
    successCriteria: "Satisfaction > 4.0 and complaints < 15",
    problemDescription:
      "Students consistently complained about declining food quality, bland taste, and limited healthy options.",
    solutionImplemented:
      "Replaced food supplier with premium vendor, introduced student feedback board for menu suggestions, added salad bar.",
    lessonsLearned: [
      "Regular supplier audits prevent quality issues",
      "Student feedback boards improve engagement",
      "Premium ingredients justify slightly higher costs",
    ],
    isPublic: true,
    studentViewCount: 245,
  },
  {
    issueId: "ISS-101",
    issueTitle: "Library AC Not Working Efficiently",
    serviceId: "library",
    serviceName: "Library",
    startDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    targetCompletionDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    currentPhase: "implementing",
    milestones: [
      {
        phase: "detected",
        completedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        completedBy: "System",
      },
      {
        phase: "investigating",
        completedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        completedBy: "Facilities Manager",
        notes: "HVAC system servicing overdue, filters clogged",
      },
      {
        phase: "implementing",
        notes: "HVAC maintenance scheduled for this week",
      },
    ],
    initialMetrics: {
      satisfactionScore: 4.5,
      complaintCount: 12,
      participationRate: 50.1,
      measurementDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    },
    problemDescription:
      "Multiple complaints about library temperature being uncomfortable during summer.",
    isPublic: false,
  },
];

// Complete Operational Dashboard
export const MOCK_OPERATIONAL_DASHBOARD: OperationalDashboard = {
  ...MOCK_ENHANCED_DASHBOARD,
  serviceParticipation: MOCK_PARTICIPATION_BY_SERVICE,
  serviceOwners: MOCK_SERVICE_OWNERS,
  improvements: [],
  studentVoices: [],
  participationTrend: [],
  segmentedAnalytics: MOCK_SEGMENTED_ANALYTICS,
  serviceBenchmarks: MOCK_BENCHMARK_SUMMARY,
  activeAlerts: MOCK_ALERTS,
  participationInsights: MOCK_PARTICIPATION_INSIGHTS,
  improvementTimelines: MOCK_IMPROVEMENT_TIMELINES,
  serviceBreakdown: MOCK_ANALYTICS.serviceBreakdown,
  managedIssues: MOCK_MANAGED_ISSUES,
  historicalComparison: MOCK_HISTORICAL_COMPARISON,
  serviceHealth: MOCK_ENHANCED_DASHBOARD.serviceHealth || [],
  aiInsights: MOCK_ENHANCED_DASHBOARD.aiInsights || [],
  weeklySummary: MOCK_ENHANCED_DASHBOARD.weeklySummary || {
    id: "weekly-summary-001",
    collegeId: "college-default-001",
    weekStart: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    weekEnd: new Date().toISOString(),
    totalFeedback: 1247,
    avgSatisfaction: 4.2,
    satisfactionChange: 0.2,
    lowestService: { name: "Online Course Portal", score: 3.8 },
    highestService: { name: "Library", score: 4.7 },
    topComplaint: "Cafeteria Wait Times Excessive",
    newIssues: 2,
    resolvedIssues: 1,
    participationRate: 45.2,
    trend: "improving",
    keyInsights: ["Satisfaction improved by 0.2 points compared to last week."],
    recommendations: ["Continue monitoring cafeteria wait times."],
    generatedAt: new Date().toISOString(),
    generatedBy: "system",
  },
};
